services:

  traefik:
    image: traefik:${TRAEFIK_VARIANT}
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_TRAEFIK_NAME}.rule=Host(`${SERVICE_TRAEFIK_FQDN}`)"
      - "traefik.http.routers.${SERVICE_TRAEFIK_NAME}.middlewares=basicAuthFile@file"
      - "traefik.http.services.${SERVICE_TRAEFIK_NAME}.loadbalancer.server.port=8080"
    ports:
      - "80:80"
      - "443:443"
      - "2222:2222"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/${ENVIRONMENT}/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/${ENVIRONMENT}/dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      - ./config/${ENVIRONMENT}/acme.json:/etc/traefik/acme.json
      - ./log/traefik:/var/log/traefik
    secrets:
      - source: admin
        target: /etc/traefik/.htpasswd

secrets:
  admin:
    file: ./config/${ENVIRONMENT}/.htpasswd
networks:
  default:
    external: false
    name: ${SERVICE_TRAEFIK_NETWORK}
