services:

  traefik:
    image: traefik:${TRAEFIK_VARIANT}
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_TRAEFIK_NAME}-http-router.rule=Host(`${SERVICE_TRAEFIK_FQDN}`)"
      - "traefik.http.routers.${SERVICE_TRAEFIK_NAME}-http-router.middlewares=basicAuthFile@file"
      - "traefik.http.routers.${SERVICE_TRAEFIK_NAME}-http-router.entryPoints=web,websecure"
      - "traefik.http.routers.${SERVICE_TRAEFIK_NAME}-http-router.service=${SERVICE_TRAEFIK_NAME}-http-service"
      - "traefik.http.services.${SERVICE_TRAEFIK_NAME}-http-service.loadbalancer.server.port=8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/${ENVIRONMENT}/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/${ENVIRONMENT}/dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      - ./config/${ENVIRONMENT}/acme.json:/etc/traefik/acme.json
      - ./log/traefik:/var/log/traefik
    secrets:
      - source: admin
        target: /etc/traefik/.htpasswd

  ssh-forwarding:
    build:
      context: forwarding
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    labels:
      - "traefik.enable=true"

      - "traefik.tcp.routers.${SERVICE_FORWARDING_NAME}-tcp-router.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.${SERVICE_FORWARDING_NAME}-tcp-router.entryPoints=ssh"
      - "traefik.tcp.routers.${SERVICE_FORWARDING_NAME}-tcp-router.service=${SERVICE_FORWARDING_NAME}-tcp-service"
      - "traefik.tcp.services.${SERVICE_FORWARDING_NAME}-tcp-service.loadbalancer.server.port=2222"

secrets:
  admin:
    file: ./config/${ENVIRONMENT}/.htpasswd

networks:
  default:
    external: false
    name: ${SERVICE_TRAEFIK_NETWORK}
