log:
  level: INFO  # ERROR, DEBUG, PANIC, FATAL, ERROR, WARN, INFO
providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
  ssh:
    address: ':2222'
global:
  checkNewVersion: true
  sendAnonymousUsage: true
experimental:
  plugins:
    keycloakopenid:
      moduleName: "github.com/Gwojda/keycloakopenid"
      version: "v0.1.35"
    header-rewrite-traefik-plugin:
      moduleName: "github.com/che-incubator/header-rewrite-traefik-plugin"
      version: "v0.1.2"