---
# set more secure TLS options,
# see https://doc.traefik.io/traefik/v2.5/https/tls/
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384

http:
  middlewares:

    basicAuthFile:
      basicAuth:
        usersFile: /etc/traefik/.htpasswd

    keycloak:
      plugin:
        keycloakopenid:
          ClientID: gitlab-oidc
          ClientSecret: client-secret
          KeycloakRealm: master
          KeycloakURL: https://auth.example.com/auth
          Scope: openid
          TokenCookieName: AUTH_TOKEN
          UseAuthHeader: "false"

tcp:
  routers:
    host-ssh-router:
      entryPoints:
        - "ssh"
      rule: "HostSNI(`console.develop.cett.dev.br`)"
      service: "host-ssh-service"
      tls: {}
  services:
    host-ssh-service:
      loadBalancer:
        servers:
          - address: "host.docker.internal:22"
