---
# set more secure TLS options,
# see https://doc.traefik.io/traefik/v2.5/https/tls/
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   # TLS 1.2
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305    # TLS 1.2
        - TLS_AES_256_GCM_SHA384                  # TLS 1.3
        - TLS_CHACHA20_POLY1305_SHA256            # TLS 1.3

        - TLS_RSA_WITH_RC4_128_SHA
        - TLS_RSA_WITH_3DES_EDE_CBC_SHA
        - TLS_RSA_WITH_AES_128_CBC_SHA
        - TLS_RSA_WITH_AES_256_CBC_SHA
        - TLS_RSA_WITH_AES_128_CBC_SHA256
        - TLS_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
        - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
        - TLS_ECDHE_RSA_WITH_RC4_128_SHA
        - TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
        - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_FALLBACK_SCSV
      curvePreferences:
        - CurveP521
        - CurveP384

http:
  middlewares:
    default:
      chain:
        middlewares:
          - default-security-headers
          - gzip
    
    secHeaders:
      chain:
        middlewares:
          - default-security-headers
          - gzip

    default-security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: https

    gzip:
      compress: {}

    basicAuthFile:
      basicAuth:
        usersFile: /etc/traefik/.htpasswd

    keycloak:
      plugin:
        keycloakopenid:
          ClientID: gitlab-oidc
          ClientSecret: client-secret
          KeycloakRealm: master
          KeycloakURL: https://auth.example.com/auth
          Scope: openid
          TokenCookieName: AUTH_TOKEN
          UseAuthHeader: "false"

    # crowdsec-bouncer:
    #   forwardauth:
    #     address: http://crowdsec-bouncer-traefik:8080/api/v1/forwardAuth
    #     trustForwardHeader: true

    cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: false
          trustip:
            - 10.0.0.0/8
            - 172.0.0.0/8
            - 192.0.0.0/8
    
    # crowdsec:
    #   plugin:
    #     bouncer:
    #       enabled: true
    #       logLevel: INFO
    #       updateIntervalSeconds: 15
    #       updateMaxFailure: 0
    #       defaultDecisionSeconds: 15
    #       httpTimeoutSeconds: 10
    #       crowdsecMode: stream
    #       crowdsecAppsecEnabled: true
    #       crowdsecAppsecHost: crowdsec:7422
    #       crowdsecAppsecFailureBlock: true
    #       crowdsecAppsecUnreachableBlock: true
          # crowdsecLapiKey: Replacekey                                  # Replace CrowdSec API key (docker exec crowdsec cscli bouncers add crowdsecBouncer)
          # crowdsecLapiKeyFile: /etc/traefik/cs-privateKey-foo
          # crowdsecLapiHost: crowdsec:8080
          # crowdsecLapiScheme: http
          # forwardedHeadersTrustedIPs:
          #   - 10.0.35.4/32                                                              # Cloudflare tunnel IP address
            # - 172.30.0.0/24                                                            # Reverse Proxy IP address 
          # clientTrustedIPs:
          #   - 10.20.10.0/24                                                              # Internal LAN IP addresses 
          #   - 10.20.15.0/24                                                              # Internal LAN IP addresses
          #   - 10.20.20.0/24                                                              # Internal LAN IP addresses
          #   - 10.20.25.0/24                                                              # Internal LAN IP addresses
          # forwardedHeadersCustomName: CF-Connecting-IP                                 # Cloudflare IP address header
