---
log:
  level: INFO  # ERROR, DEBUG, PANIC, FATAL, ERROR, WARN, INFO
  filePath: "/var/log/traefik/traefik.log"
  format: json
  maxSize: 1
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https      
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: letsencrypt
  ssh:
    address: ':22'
serversTransport:
  insecureSkipVerify: true
certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
global:
  checkNewVersion: true
  sendAnonymousUsage: true
experimental:
  plugins:
    keycloakopenid:
      moduleName: "github.com/Gwojda/keycloakopenid"
      version: "v0.1.35"
    header-rewrite-traefik-plugin:
      moduleName: "github.com/che-incubator/header-rewrite-traefik-plugin"
      version: "v0.1.2"
    cloudflarewarp:
      moduleName: "github.com/BetterCorp/cloudflarewarp"
      version: "v1.3.3"