filenames:
  - /var/log/traefik/*
labels:
  type: traefik
---
filenames:
  - /var/log/auth.log
  - /var/log/syslog
  - /var/log/kern.log
labels:
  type: syslog
---
listen_addr: 0.0.0.0:7422
appsec_config: crowdsecurity/virtual-patching
name: myAppSecComponent
source: appsec
labels:
  type: appsec
---
source: docker
container_name:
 - auth-keycloak-1
#container_id:
# - 843ee92d231b
labels:
  type: keycloak
---
filenames:
  - /var/log/bitwarden/identity.log
labels:
  type: bitwarden